# Generated by Django 4.2.16 on 2024-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
            ],
        ),
    ]
