# Generated by Django 4.2.16 on 2024-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_listings_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="image_url",
            field=models.URLField(default="/media/images/banner.jpg"),
        ),
        migrations.AlterField(
            model_name="listings",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
