# Generated by Django 4.2.16 on 2024-10-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_listings_image_url_alter_listings_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="image_url",
        ),
    ]
